- robot:
    #Choose robot (Available: 'ur10', 'kuka', 'wam', 'franka')
    robot_name: "ur10"
- scene:
      position: [-0.2, 0.0, 0.08] # [ 0.85, -0.15, 0.834] # [-0.2, 0, -0.2] # [ 0.625, 0.275, 0.85 ] #  #   # [ 0.625, 0.275, 0.85 ] # [ 0.62, -0.15, 0.834] # [ 0.625, 0.275, 0.85 ] # [ 0.62, -0.15, 0.85 ] # [ 0.55, -0.0, 0.75] # [ 0.85, -0.15, 0.834] # [ 0.95, -0.15, 0.834]
      orientation: [ 0.0, 0.0, 0.0, 1.0 ]
      environment_name: "industrial"
      objects: []
      objects_position: []
      objects_orientation: []
      problemset: "industrial"
      sdf_name: "industrial_vgpmp"
- trainable_params:
    q_mu: True
    q_sqrt: True
    lengthscales: True
    kernel_variance: True
    sigma_obs: False
    inducing_variable: False
    alpha: False
- graphics:
    visuals: True
    quality: high
    GUI: True
    debug_joint_positions: False
    debug_sphere_positions: False
    visualize_best_sample: True
    visualize_ee_path_uncertainty: False
    visualize_drawn_samples: False