- robot:
    #Choose robot (Available: 'ur10', 'kuka', 'wam', 'franka')
    robot_name: "franka"
- scene:
    # [-0.2, 0, 0.08] industrial wam and ur10
    # [-0.2, 0, -0.2] industrial kuka and franka
    # [ 0.62, -0.15, 0.834] bookshelves franka
    # [ 0.7, -0.15, 0.834] bookshelves kuka
    # [ 0.85, -0.15, 0.834] bookshelves wam
    # [ 0.95, -0.15, 0.834] bookshelves ur10
    object_position: [-0.2, 0, -0.2] # [-0.2, 0, -0.2] #   [ 0.625, 0.275, 0.85 ] # [-0.2, 0, 0.08] #  [ 0.62, -0.15, 0.834]  # [ 0.625, 0.275, 0.85 ] # [ 0.62, -0.15, 0.85 ] #    # [ 0.55, -0.0, 0.75] # [ 0.85, -0.15, 0.834] # [ 0.95, -0.15, 0.834] 
    object_name: "industrial.urdf"
    problemset: "industrial"
    sdf_name: "industrial_vgpmp.sdf"
- trainable_parameters:
    q_mu: True
    q_sqrt: True
    lengthscales: True
    kernel_variance: True
    sigma_obs: False
    inducing_variable: True
    alpha: False
- graphics:
    visuals: True
    quality: high
    GUI: True
    debug_joint_positions: False
    debug_sphere_positions: False
    visualize_best_sample: True
    visualize_ee_path_uncertainty: False
    visualize_drawn_samples: True