- robot:
    #Choose robot (Available: 'ur10', 'kuka', 'wam', 'franka')
    robot_name: "wam"
    robot_start_pos: [0, 0, 1.0292]
    robot_start_orientation_euler: [0, 0, 0]
- scene:
    object_position: [ 0.625, 0.275, 0.85 ] # [ 0.62, -0.15, 0.85 ] # [-0.2, 0, -0.2] #    # [ 0.55, -0.0, 0.75]
    object_name: "bookshelves_table_mesh_gpmp.urdf"
    problemset: "bookshelves"
    sdf_name: "bookshelves_table_gpmp.sdf"
- planner:
    num_samples: 7
    sigma_obs: 0.004
    num_inducing: 25
    num_spheres: 15 # should be dependent on robot
    learning_rate: 0.09
    alpha: 10
    num_steps: 130
    lengthscale: 900
- graphics:
    visuals: True
    quality: high
    GUI: True
