- robot:
    #Choose robot (Available: 'ur10', 'kuka', 'wam', 'franka')
    robot_name: "wam"
    robot_start_pos: [ 0, 0, 0 ]
    robot_start_orientation_euler: [ 0, 0, 0 ]
- scene:
    object_position: [ 0.62, -0.15, 0.85 ] # [-0.2, 0, -0.2] #    # [ 0.55, -0.0, 0.75]
    object_name: "bookshelves_table_mesh.urdf"
    problemset: "bookshelves"
    sdf_name: "bookshelves_table_center-acdd_vgpmp.sdf"
- planner:
    num_samples: 15
    sigma_obs: 0.005
    num_inducing: 10
    num_spheres: 37 # should be dependent on robot
    learning_rate: 0.1
    alpha: 1.75
    num_steps: 150
    lengthscale: 90
- graphics:
    visuals: True
    quality: high
    GUI: True
