- robot:
    #Choose robot (Available: 'ur10', 'kuka', 'wam', 'franka')
    robot_name: "kuka"
- scene:
    object_position: [-0.2, 0, -0.2]  # [ 0.62, -0.15, 0.834]  # [ 0.625, 0.275, 0.85 ] # [ 0.62, -0.15, 0.85 ] #    # [ 0.55, -0.0, 0.75]
    object_name: "industrial.urdf"
    problemset: "industrial"
    sdf_name: "industrial_vgpmp.sdf"
- trainable_parameters:
    q_mu: True
    q_sqrt: True
    lengthscales: True
    kernel_variance: True
    sigma_obs: False
    inducing_variable: False
    alpha: True
- graphics:
    visuals: True
    quality: high
    GUI: True
    debug_joint_positions: False
    debug_sphere_positions: False
    visualize_best_sample: True
    visualize_ee_path_uncertainty: False
    visualize_drawn_samples: False